# Generated by Django 3.2.12 on 2022-03-21 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Organization Name')),
                ('tagline', models.TextField(verbose_name='Organization Tagline')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='organization_avatars')),
            ],
        ),
    ]
