# Generated by Django 3.2.12 on 2022-04-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tagline',
            field=models.TextField(verbose_name='organization tagline'),
        ),
    ]
