# Generated by Django 3.2.12 on 2022-04-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
