# Generated by Django 3.2.12 on 2022-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220219_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
